spring.application.name=SpringSimple
# JWT secret key (must be Base64 encoded, 256-bit+)
jwt.secret=Y2VydGlmaWNhdGVzLXNlY3JldC1rZXktbXVzdC1iZS1iYXNlNjQtYW5kLWxvbmc=

# Token validity time in milliseconds (example: 1 hour)
jwt.expiration=3600000